import {
  Lead,
  Campaign,
  EmailDraft,
  ResearchProfile,
  Sequence,
  ActivityEvent,
} from "@/types";

export const MOCK_METRICS = {
  totalLeads: 48,
  activeCampaigns: 3,
  emailsAwaitingApproval: 7,
  emailsSent: 124,
  replies: 14,
  sequencesStopped: 6,
  isPlaceholder: true,
};

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "camp-001",
    user_id: "user-001",
    name: "US Mid-Market Logistics — Q2 Outbound",
    description: "Targeting VP of Logistics and Operations at 100-500 person freight brokers.",
    icp_description: "Mid-market freight and logistics operations expanding regional fleet capacity.",
    offer_description: "Automated route evidence engine and exception triage platform.",
    target_region: "North America (US East & Midwest)",
    campaign_objective: "Initiate dialogue around dispatch bottleneck friction during seasonal surges.",
    status: "active",
    lead_count: 24,
    active_sequences_count: 18,
    replies_count: 8,
    created_at: "2026-04-12T10:00:00Z",
    updated_at: "2026-04-20T14:30:00Z",
  },
  {
    id: "camp-002",
    user_id: "user-001",
    name: "Fintech Compliance Officers — US Expansion",
    description: "Reaching out to newly appointed Compliance Directors at Series B fintechs.",
    icp_description: "Series B+ fintech companies scaling cross-border settlement teams.",
    offer_description: "Pre-audit automated transaction surveillance and reporting.",
    target_region: "United States",
    campaign_objective: "Establish conversations regarding audit preparation overhead.",
    status: "active",
    lead_count: 16,
    active_sequences_count: 12,
    replies_count: 5,
    created_at: "2026-04-15T09:00:00Z",
    updated_at: "2026-04-21T11:15:00Z",
  },
  {
    id: "camp-003",
    user_id: "user-001",
    name: "B2B SaaS DevSecOps — Hiring Signals",
    description: "Trigger-based outreach to VP Engineering actively hiring AppSec leads.",
    icp_description: "B2B SaaS 50-250 employees with active AppSec hiring signals.",
    offer_description: "Continuous developer security review guardrails.",
    target_region: "US & Canada",
    campaign_objective: "Open dialogue on developer security review bottlenecks.",
    status: "draft",
    lead_count: 8,
    active_sequences_count: 0,
    replies_count: 1,
    created_at: "2026-04-18T16:20:00Z",
    updated_at: "2026-04-18T16:20:00Z",
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-001",
    user_id: "user-001",
    account_id: "acc-001",
    campaign_id: "camp-001",
    first_name: "Marcus",
    last_name: "Vance",
    email: "marcus.vance@apexlogistics-demo.com",
    job_title: "VP of Operations",
    company_name: "Apex Logistics Group",
    linkedin_url: "https://linkedin.com/in/demo-marcus-vance",
    country: "United States",
    industry: "Freight & Logistics",
    lead_objective: "Discuss carrier onboarding delays during their Midwest hub expansion.",
    email_status: "valid",
    outreach_status: "in_progress",
    approval_status: "pending",
    reply_status: "none",
    stop_sequence: false,
    current_step: 1,
    next_action: "awaiting_approval_touch_1",
    next_action_date: "2026-05-02T14:00:00Z",
    created_at: "2026-04-28T08:15:00Z",
    updated_at: "2026-04-28T09:30:00Z",
  },
  {
    id: "lead-002",
    user_id: "user-001",
    account_id: "acc-002",
    campaign_id: "camp-001",
    first_name: "Elena",
    last_name: "Rostova",
    email: "elena.r@swiftfreight-demo.com",
    job_title: "Director of Fleet Strategy",
    company_name: "SwiftFreight Systems",
    linkedin_url: "https://linkedin.com/in/demo-elena-rostova",
    country: "United States",
    industry: "Freight & Logistics",
    lead_objective: "Validate if route exception handling is scaling with their recent carrier acquisition.",
    email_status: "valid",
    outreach_status: "in_progress",
    approval_status: "approved",
    reply_status: "none",
    stop_sequence: false,
    current_step: 2,
    next_action: "dispatch_touch_2",
    next_action_date: "2026-05-03T10:00:00Z",
    created_at: "2026-04-25T11:00:00Z",
    updated_at: "2026-04-29T15:10:00Z",
  },
  {
    id: "lead-003",
    user_id: "user-001",
    account_id: "acc-003",
    campaign_id: "camp-002",
    first_name: "David",
    last_name: "Chen",
    email: "d.chen@novapay-demo.com",
    job_title: "Head of Compliance & Risk",
    company_name: "NovaPay Financial",
    linkedin_url: "https://linkedin.com/in/demo-david-chen",
    country: "United States",
    industry: "Fintech",
    lead_objective: "Explore how transaction surveillance workload is managed after Series B announcement.",
    email_status: "valid",
    outreach_status: "stopped",
    approval_status: "approved",
    reply_status: "replied_interested",
    stop_sequence: true,
    current_step: 2,
    next_action: "sequence_stopped_reply",
    next_action_date: null,
    created_at: "2026-04-20T09:30:00Z",
    updated_at: "2026-04-27T16:45:00Z",
  },
  {
    id: "lead-004",
    user_id: "user-001",
    account_id: "acc-004",
    campaign_id: "camp-002",
    first_name: "Sarah",
    last_name: "Jenkins",
    email: "sarah.j@crestbank-demo.com",
    job_title: "VP Regulatory Affairs",
    company_name: "Crest Financial",
    linkedin_url: "https://linkedin.com/in/demo-sarah-jenkins",
    country: "United States",
    industry: "Fintech",
    lead_objective: "Determine audit prep overhead for cross-border ACH compliance.",
    email_status: "valid",
    outreach_status: "in_progress",
    approval_status: "pending",
    reply_status: "none",
    stop_sequence: false,
    current_step: 1,
    next_action: "awaiting_approval_touch_1",
    next_action_date: "2026-05-02T16:00:00Z",
    created_at: "2026-04-29T10:20:00Z",
    updated_at: "2026-04-29T11:05:00Z",
  },
];

export const MOCK_EMAILS_FOR_APPROVAL: EmailDraft[] = [
  {
    id: "email-001",
    sequence_id: "seq-001",
    lead_id: "lead-001",
    lead_name: "Marcus Vance",
    lead_email: "marcus.vance@apexlogistics-demo.com",
    lead_company: "Apex Logistics Group",
    step_number: 1,
    strategic_purpose: "relevance",
    subject_line: "Apex's Midwest hub expansion & dispatch triage",
    preview_text: "Observing carrier onboarding across new routes",
    body_generated:
      "Saw Apex recently opened the new regional distribution hub in Columbus to handle expanded freight routes.\nTeams expanding terminal density often find dispatchers spending hours reconciling carrier exceptions across fragmented systems.\nWe helped regional operators cut exception handling time by half while maintaining on-time fulfillment rates across new lanes.\nWould it be worth comparing notes on how you're handling route visibility during this expansion?",
    body_approved: null,
    ps_text: "PS: Noticed your recent panel discussion on Midwest supply chain resilience.",
    qa_score: 46,
    approval_status: "pending_approval",
    sending_status: "unapproved",
    generated_at: "2026-04-28T09:30:00Z",
    approved_at: null,
    scheduled_at: null,
    sent_at: null,
    created_at: "2026-04-28T09:30:00Z",
    updated_at: "2026-04-28T09:30:00Z",
  },
  {
    id: "email-002",
    sequence_id: "seq-004",
    lead_id: "lead-004",
    lead_name: "Sarah Jenkins",
    lead_email: "sarah.j@crestbank-demo.com",
    lead_company: "Crest Financial",
    step_number: 1,
    strategic_purpose: "relevance",
    subject_line: "Crest's cross-border rollout & audit surveillance",
    preview_text: "Scaling transaction monitoring workload",
    body_generated:
      "Saw Crest Financial recently announced the expansion of multi-currency cross-border settlement.\nCompliance teams scaling settlement volume frequently see manual exception review creating backlogs before quarterly audits.\nSimilar fintech teams established automated pre-audit surveillance that reduced reporting turnaround from days to under four hours.\nCurious if audit prep overhead is something your team is currently seeing as volume grows?",
    body_approved: null,
    ps_text: null,
    qa_score: 44,
    approval_status: "pending_approval",
    sending_status: "unapproved",
    generated_at: "2026-04-29T11:05:00Z",
    approved_at: null,
    scheduled_at: null,
    sent_at: null,
    created_at: "2026-04-29T11:05:00Z",
    updated_at: "2026-04-29T11:05:00Z",
  },
];

export const MOCK_RESEARCH_PROFILES: ResearchProfile[] = [
  {
    id: "res-001",
    lead_id: "lead-001",
    lead_name: "Marcus Vance",
    company_name: "Apex Logistics Group",
    observed_facts: [
      {
        fact: "Announced opening of new 250k sq ft Midwest logistics hub in Columbus, OH",
        source_type: "press_release",
        source_title: "Apex Logistics Group Q1 Operational Expansion Announcement",
        source_url: null,
        source_date: "2026-03-12",
        notes: "Targeting 40% increase in regional freight transit throughput",
        confidence: 1.0,
      },
      {
        fact: "Active job postings for 6 Logistics Coordinators and 2 Regional Dispatchers",
        source_type: "job_posting",
        source_title: "Careers Portal: Operations & Logistics Roles",
        source_url: null,
        source_date: "2026-04-05",
        notes: "Focus on carrier onboarding and exception routing",
        confidence: 0.95,
      },
    ],
    reasonable_inferences: [
      {
        inference: "Dispatch operations are currently managing fragmented carrier communication across legacy TMS tools during terminal ramp-up",
        premise: "Rapid capacity addition paired with simultaneous hiring of coordinators indicates operational scaling strain",
        source_type: "synthesis",
        source_title: "Capacity Expansion Friction Analysis",
        source_url: null,
        source_date: "2026-04-28",
        notes: "Standard operational bottleneck during terminal opening phases",
      },
    ],
    unknowns: [
      {
        topic: "Current Transportation Management System (TMS)",
        notes: "Specific vendor or proprietary status unverified from public sources",
      },
    ],
    business_trigger: "Opening of new Columbus Midwest distribution hub with rapid carrier onboarding",
    trigger_source_type: "press_release",
    trigger_source_title: "Apex Logistics Group Expansion Release",
    trigger_source_date: "2026-03-12",
    problem_hypothesis: "Dispatchers spending excessive manual hours managing carrier exceptions across new regional lanes.",
    business_consequence: "Potential on-time delivery SLA breaches and driver churn during initial facility ramp.",
    future_state: "Unified exception triage reducing manual check-calls by 50% across expanding corridors.",
    personalization_angle: "Midwest hub expansion + dispatch capacity",
    research_status: "completed",
    created_at: "2026-04-28T09:00:00Z",
    updated_at: "2026-04-28T09:15:00Z",
  },
];

export const MOCK_SEQUENCES: Sequence[] = [
  {
    id: "seq-001",
    campaign_id: "camp-001",
    lead_id: "lead-001",
    lead_name: "Marcus Vance",
    lead_company: "Apex Logistics Group",
    campaign_name: "US Mid-Market Logistics — Q2 Outbound",
    current_step: 1,
    status: "active",
    next_action: "awaiting_approval_touch_1",
    next_action_date: "2026-05-02T14:00:00Z",
    started_at: "2026-04-28T09:30:00Z",
    stopped_at: null,
    stop_reason: null,
    created_at: "2026-04-28T09:30:00Z",
    updated_at: "2026-04-28T09:30:00Z",
  },
  {
    id: "seq-002",
    campaign_id: "camp-001",
    lead_id: "lead-002",
    lead_name: "Elena Rostova",
    lead_company: "SwiftFreight Systems",
    campaign_name: "US Mid-Market Logistics — Q2 Outbound",
    current_step: 2,
    status: "active",
    next_action: "dispatch_touch_2",
    next_action_date: "2026-05-03T10:00:00Z",
    started_at: "2026-04-25T11:00:00Z",
    stopped_at: null,
    stop_reason: null,
    created_at: "2026-04-25T11:00:00Z",
    updated_at: "2026-04-29T15:10:00Z",
  },
  {
    id: "seq-003",
    campaign_id: "camp-002",
    lead_id: "lead-003",
    lead_name: "David Chen",
    lead_company: "NovaPay Financial",
    campaign_name: "Fintech Compliance Officers — US Expansion",
    current_step: 2,
    status: "stopped_replied",
    next_action: null,
    next_action_date: null,
    started_at: "2026-04-20T09:30:00Z",
    stopped_at: "2026-04-27T16:45:00Z",
    stop_reason: "inbound_reply_received",
    created_at: "2026-04-20T09:30:00Z",
    updated_at: "2026-04-27T16:45:00Z",
  },
];

export const MOCK_ACTIVITIES: ActivityEvent[] = [
  {
    id: "act-001",
    user_id: "user-001",
    lead_id: "lead-003",
    lead_name: "David Chen (NovaPay Financial)",
    email_id: "email-003",
    campaign_id: "camp-002",
    activity_type: "reply_detected",
    metadata: {
      classification: "interested",
      thread_id: "th-demo-789",
      snippet: "Thanks for reaching out. We are indeed seeing this backlog. Open to comparing notes next week.",
    },
    created_at: "2026-04-27T16:45:00Z",
  },
  {
    id: "act-002",
    user_id: "user-001",
    lead_id: "lead-003",
    lead_name: "David Chen (NovaPay Financial)",
    email_id: null,
    campaign_id: "camp-002",
    activity_type: "sequence_stopped",
    metadata: {
      reason: "inbound_reply",
      stopped_at_step: 2,
    },
    created_at: "2026-04-27T16:45:10Z",
  },
  {
    id: "act-003",
    user_id: "user-001",
    lead_id: "lead-001",
    lead_name: "Marcus Vance (Apex Logistics Group)",
    email_id: "email-001",
    campaign_id: "camp-001",
    activity_type: "qa_completed",
    metadata: {
      qa_score: 46,
      passed: true,
      attempts: 1,
    },
    created_at: "2026-04-28T09:30:00Z",
  },
  {
    id: "act-004",
    user_id: "user-001",
    lead_id: "lead-002",
    lead_name: "Elena Rostova (SwiftFreight Systems)",
    email_id: "email-005",
    campaign_id: "camp-001",
    activity_type: "email_sent",
    metadata: {
      step_number: 1,
      strategic_purpose: "relevance",
    },
    created_at: "2026-04-25T11:00:00Z",
  },
];
